<!--
    2021_09_07_5
    try except
    script 부분을 head 안에 작성했을 경우
    body 부분이 실행되기 전이기 때문에 demo_err를 찾지 못해 p 태그의 값이 변하지 않는다.
    head 안에 작성할 경우 뒤에서 다시 실행
-->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script>
        function first_start() {
            try {
                aalert("hello welcome");
            } catch(err) {
                document.getElementById("demo_err").innerHTML = err.message;
            }
        }
    </script>
</head>
<body>
    <p id = "demo_err" onmouseover = "this.style.backgroundColor = 'orange'">에러내용</p>
    <script>first_start()</script>
</body>
</html>